TOOLS_SCHEMA = [
    {
        "type":"function",
        "function":{
            "name":"calculator",
            "description":"执行数学计算。支持+-*/、**、sqrt、sin等。",
            "parameters":{
                "type":"object",
                "properties":{
                    "expression":{"type":"string","description":"数学表达式"}
                },
                "required":["expression"]
            }
        }
    },
    {
        "type":"function",
        "function":{
            "name":"read_excel",
            "description":"excel文件查询器，返回表格内数据",
            "parameters":{
                "type":"object",
                "properties":{
                    "filename":{"type":"string","decription":"要查询文件的名字"},
                    "sheet_name":{"type":"string","decription":"要查询的表名"}
                },
                "required":["filename","sheet_name"]
            }
        }
    },
    {
        "type":"function",
        "function":{
            "name":"web_search",
            "decription":"联网搜索信息。用于查找竞品动态、行业资讯、外部信息。",
            "parameters":{
                "type":"object",
                "properties":{
                    "query":{"type":"string","description":"要查询的内容"}
                },
                "required":["query"]
            }
        }
    }
]